#!/bin/bash -e

[[ -n $REDIS_HOST ]] || REDIS_HOST=redis
[[ -n $REDIS_PORT ]] || REDIS_PORT=6379
[[ -n $REDIS_DATABASE ]] || REDIS_DATABASE=0
[[ -n $LOG_LEVEL ]] || LOG_LEVEL=INFO
[[ -n $LOADER ]] || LOADER=remotecv.http_loader
[[ -n $STORE ]] || STORE=remotecv.result_store.redis_store

if [ -n "$TIMEOUT" ]; then
  TIMEOUT_PARAMETER="-t $TIMEOUT"
fi

if [ -n "$SENTRY_URL" ]; then
  SENTRY_URL_PARAMETER="--sentry_url $SENTRY_URL"
fi

if [ "$1" = 'remotecv' ]; then
  exec remotecv --backend pyres --host $REDIS_HOST --port $REDIS_PORT --database $REDIS_DATABASE -l $LOG_LEVEL -o $LOADER -s $STORE $TIMEOUT_PARAMETER $SENTRY_URL_PARAMETER
fi

exec "$@"
